"""Add User model and update ContactFormMessage with user_clerk_id

Revision ID: 89250d7d2cae
Revises: 8fe422b0808c
Create Date: 2025-07-11 16:10:30.813581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '89250d7d2cae'
down_revision: Union[str, Sequence[str], None] = '8fe422b0808c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.add_column('contactformmessage', sa.Column('user_clerk_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_index(op.f('ix_contactformmessage_user_id'), table_name='contactformmessage')
    op.create_index(op.f('ix_contactformmessage_email'), 'contactformmessage', ['email'], unique=False)
    op.create_index(op.f('ix_contactformmessage_user_clerk_id'), 'contactformmessage', ['user_clerk_id'], unique=False)
    op.create_foreign_key(None, 'contactformmessage', 'user', ['user_clerk_id'], ['clerk_user_id'])
    op.drop_column('contactformmessage', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactformmessage', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contactformmessage', type_='foreignkey')
    op.drop_index(op.f('ix_contactformmessage_user_clerk_id'), table_name='contactformmessage')
    op.drop_index(op.f('ix_contactformmessage_email'), table_name='contactformmessage')
    op.create_index(op.f('ix_contactformmessage_user_id'), 'contactformmessage', ['user_id'], unique=False)
    op.drop_column('contactformmessage', 'user_clerk_id')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
