"""Add AnalysisModel and SimulationModel tables

Revision ID: 91a19ac87ade
Revises: f58c7f441160
Create Date: 2025-07-16 15:16:00.109632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '91a19ac87ade'
down_revision: Union[str, Sequence[str], None] = 'f58c7f441160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_clerk_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('analysis_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('analysis_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('is_admin_analysis', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_clerk_id'], ['user.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_model_analysis_type'), 'analysis_model', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_model_is_public'), 'analysis_model', ['is_public'], unique=False)
    op.create_index(op.f('ix_analysis_model_user_clerk_id'), 'analysis_model', ['user_clerk_id'], unique=False)
    op.create_table('simulation_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_clerk_id', sa.String(length=255), nullable=True),
    sa.Column('simulation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('simulation_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('execution_metadata', sa.JSON(), nullable=True),
    sa.Column('is_admin_simulation', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_clerk_id'], ['user.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_model')
    op.drop_index(op.f('ix_analysis_model_user_clerk_id'), table_name='analysis_model')
    op.drop_index(op.f('ix_analysis_model_is_public'), table_name='analysis_model')
    op.drop_index(op.f('ix_analysis_model_analysis_type'), table_name='analysis_model')
    op.drop_table('analysis_model')
    # ### end Alembic commands ###
