"""empty message

Revision ID: a1ddfc8b957a
Revises: aaeb2dabbcb4
Create Date: 2025-07-09 09:48:58.574964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1ddfc8b957a'
down_revision: Union[str, Sequence[str], None] = 'aaeb2dabbcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactformmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactformmessage_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactformmessage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_contactformmessage_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
