"""Add Lotto6aus49Draw model for lottery data

Revision ID: f58c7f441160
Revises: 89250d7d2cae
Create Date: 2025-07-14 15:04:49.944559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f58c7f441160'
down_revision: Union[str, Sequence[str], None] = '89250d7d2cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto6aus49draw',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('draw_day', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('numbers', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('super_number', sa.Integer(), nullable=False),
    sa.Column('spiel77', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('super6', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotto6aus49draw')
    # ### end Alembic commands ###
